### ISSUE TITLE
nullable attaribute is not implemented for anything else then ObjectElement properties

### ISSUE THREAD

**Issue by klokane** [apiaryio/drafter#202]
Nullable does not work for following use cases
```apib
# Data Structures

# ArrayWithNullable (array)
- m (nullable)

# NullableString (string, nullable)
```

**Comment by pksunkara** [comment]
This is fixed by #201

**Comment by klokane** [comment]
This is not fixed #201 implements `nullable` just for properties (MemeberElement), other kinds of elements are still not imlemented

**Comment by kylef** [comment]
I can confirm string is now implemented:

```apib
+ Response 200 (application/json)
    + Attributes (string, nullable)
```

Message Body Schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "anyOf": [
    {
      "type": "null"
    },
    {
      "type": "string"
    }
  ]
}
```

Message Body:

```json
null
```

Array doesn't appear to be implemented.
